// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6keS8xIZmL80ThQ-uQiH-Y_pJ4xjwDNY',
    appId: '1:30120796562:web:11e7f99a2c4ea07c6b614b',
    messagingSenderId: '30120796562',
    projectId: 'carebridge-11d41',
    authDomain: 'carebridge-11d41.firebaseapp.com',
    storageBucket: 'carebridge-11d41.firebasestorage.app',
    measurementId: 'G-0G6JLH2ZPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGoL586CaSKSvsYRhPLjrXgumtLCWuK6g',
    appId: '1:30120796562:android:fa6befd67abe1ab56b614b',
    messagingSenderId: '30120796562',
    projectId: 'carebridge-11d41',
    storageBucket: 'carebridge-11d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCozCCNRUKC0iXI3AfNCcJz6bAj9VMXo3Y',
    appId: '1:30120796562:ios:ddbb08e2c0c50f2c6b614b',
    messagingSenderId: '30120796562',
    projectId: 'carebridge-11d41',
    storageBucket: 'carebridge-11d41.firebasestorage.app',
    iosBundleId: 'my.edu.tarc.careBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCozCCNRUKC0iXI3AfNCcJz6bAj9VMXo3Y',
    appId: '1:30120796562:ios:ddbb08e2c0c50f2c6b614b',
    messagingSenderId: '30120796562',
    projectId: 'carebridge-11d41',
    storageBucket: 'carebridge-11d41.firebasestorage.app',
    iosBundleId: 'my.edu.tarc.careBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6keS8xIZmL80ThQ-uQiH-Y_pJ4xjwDNY',
    appId: '1:30120796562:web:11e7f99a2c4ea07c6b614b',
    messagingSenderId: '30120796562',
    projectId: 'carebridge-11d41',
    authDomain: 'carebridge-11d41.firebaseapp.com',
    storageBucket: 'carebridge-11d41.firebasestorage.app',
    measurementId: 'G-0G6JLH2ZPL',
  );

}